apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 365849706370.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 365849706370.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 8b644be0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
